# Generated by Django 3.1.9 on 2022-03-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default',
            field=models.BooleanField(default=False, help_text='by default=False'),
        ),
    ]
